# Generated by Django 3.0.5 on 2020-04-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smsonattente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('next_date_send', models.DateField()),
                ('name', models.CharField(max_length=60)),
                ('id_pv', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='smstosend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('num_phone', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('body_sms', models.TextField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_pv', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='sys_paramt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pr_value', models.CharField(max_length=100)),
                ('pr_name', models.CharField(max_length=60)),
            ],
        ),
    ]
