# Generated by Django 3.0.5 on 2020-05-20 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1_sms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sys_paramt',
            name='pr_name',
        ),
    ]
