# Generated by Django 3.0.5 on 2020-05-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_sms', '0002_remove_sys_paramt_pr_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsonattente',
            name='data',
            field=models.CharField(default='e', max_length=800),
        ),
    ]
